matrix:
  include:
    - language: node_js
      before_script:
        - cd frontend
      script: 
        - npm install
        - npm build

    - language: java
      jdk: oraclejdk8
      before_script:
        - cd backend
      script: 
        - cd ../backend
        - mvn clean package

cache:
  directories:
  - node_modules