matrix:
  include:
    - language: node_js
      node_js:
        - "11"
      before_script:
        - cd frontend
      script: 
        - npm install
        - npm build
      cache:
        directories:
        - node_modules
     
      before_script:
        - cd backend
      script: 
        - cd ../backend
    - language: java
      jdk: oraclejdk8
      cache:
        directories:
          - $HOME/.m2
      script: 
        - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.projectKey=guhcostan_projetoWeb -Dsonar.organization=guhcostan-github -Dsonar.host.url=https://sonarcloud.io  -Dsonar.login=$SONAR_TOKEN
      deploy:
        provider: heroku
        api-key: 
          secure: $HEROKU_API_KEY
        app: seisvue
