matrix:
  include:
    - language: node_js
      node_js:
        - "11"
      before_script:
        - cd frontend
      script: 
        - npm install
        - npm build
      cache:
        directories:
        - node_modules

    - language: java
      jdk: oraclejdk8
      before_script:
        - cd backend
      script: 
        - cd ../backend
        - mvn clean package